### ISSUE TITLE
2.7.1 影像回收/辨識狀況

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-webapp#16]
- [x] a. 列出樣區
- [x] d. 顯示樣區名稱
- [x] e. 顯示最後更新時間
- [x] f. 切換年份，得到該年資料呈現在圖表上
- [x] i. 切換帶入影像辨識進度資料

文件：
- [辨識狀況](https://github.com/TaiBIF/camera-trap-api/wiki/identification-status)
- [回收狀況](https://github.com/TaiBIF/camera-trap-api/wiki/retrieval-status)

**Comment by diabloevagto** [comment]
api 缺少最後更新時間

**Comment by AJANelson** [comment]
已有畫面，待驗證

**Comment by oahehc** [comment]
是否需要提供 API for 樣區/子樣區名單
![image](https://user-images.githubusercontent.com/13633490/48947726-0dfda300-ef6d-11e8-9714-f8cee23cd08f.png)

**Comment by diabloevagto** [comment]
目前是自己湊出來的可以參考 `project/cameraLocations`，不過這部分湊的方式很難看
如果直接有 api 取得是最好的

除了樣區跟子樣區以外，也要補上相機位置

**Comment by oahehc** [comment]
`最後更新時間`是顯示該專案最後更新時間, 還是針對目前篩選樣區/子樣區?
若是針對目前篩選條件, 最後更新時間會放在哪支API?
![image](https://user-images.githubusercontent.com/13633490/48948651-32a74a00-ef70-11e8-9466-054d3a71dc75.png)

```
影像辨識狀況 (特定年度特定計畫) WF 2.6, WF 2.7, WF 2.8
 /project/location-month-identified-num
影像回收狀況 (特定年度特定計畫) WF 2.6, WF 2.7, WF 2.8
 /project/location-month-retrieved-num
```

**Comment by cjk-halodule** [comment]
應該是目前篩選樣區/子樣區的
最後更新時間應該是目前該樣區的最新資料時間 (@rwu823 這個可能是待做的 API)

**Comment by oahehc** [comment]
i. 切換帶入影像辨識進度資料
wireframe 圖表是顯示每個月 `已辨識` / `資料未完整` 兩種狀態,
但 API 給的是每個月的數量, 這段不清楚應該如何串接

### API
```
影像辨識狀況 (特定年度特定計畫) WF 2.6, WF 2.7, WF 2.8
 /project/location-month-identified-num
...
      "monthly_num": [
        {
          "month": 3,
          "num": 6
        },
        {
          "month": 2,
          "num": 115
        },
        {
          "month": 1,
          "num": 21
        }
      ],
...
```
### Wireframe
![image](https://user-images.githubusercontent.com/13633490/48974779-1ead3680-f09d-11e8-9ba7-6e2aead239af.png)

**Comment by cjk-halodule** [comment]
這個以 API 的現況應該要配合 location-month-retrieved-num
需要比較 monthly_num 中是否有同個一 month 值的物件

如果兩者都有同一個月份的物件，那麼長條圖就可以畫到有 month 值最大的那個月
顏色部分則需要比較同一個月的 num，一樣的話就是藍色，不一樣的話就是灰色

這樣可以瞭解？

**Comment by oahehc** [comment]
如果兩支 api 的 month 不一致, 是統一歸屬到灰色, 還是有其他處理邏輯？

**Comment by cjk-halodule** [comment]
應該是以 retrieved-num 統一歸屬到灰色
(不過 retrieved 的意義我們在後端 api 會再確認過)

**Comment by oahehc** [comment]
請問以下理解正確嗎？
retrieved-num / location-month-identified-num 該月份都有資料
- 兩者數量相同, 則歸為 `當月資料已辨識`
- 數量不同, 則歸為 `當月資料已辨識, 但資料未完整`

**Comment by cjk-halodule** [comment]
yes :)

**Comment by oahehc** [comment]
影像回收狀況：圖表有三種狀態, API 目前只有一個數量, 請問要如何對應？
![image](https://user-images.githubusercontent.com/13633490/49082573-10217380-f285-11e8-875b-32dce7ceb576.png)

**Comment by cjk-halodule** [comment]
https://github.com/TaiBIF/camera-trap-api/wiki/retrieval-status
就我的理解是如果資料長這樣：
```
      "monthly_num": [
        {
          "month": 4,
          "num": 33
        },
        {
          "month": 3,
          "num": 6
        },
        {
          "month": 2,
          "num": 115
        }
      ],
```
那就會是上面花蓮處的情況，因為一月沒有結果。

**Comment by oahehc** [comment]
所以不會有`相機撤除`這個情況？

**Comment by cjk-halodule** [comment]
會 但得確認算是法 可先不處理

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oahehc** [comment]
`會 但得確認算法 可先不處理`
建議是否先定義 response 格式, 以免後續要增加時會影響到其他兩個類別的計算？

**Comment by cjk-halodule** [comment]
相機撤除本年度不處理。https://github.com/TaiBIF/camera-trap-webapp/issues/83

格式已更新在 [回收狀況](https://github.com/TaiBIF/camera-trap-api/wiki/retrieval-status) 及 [辨識狀況](https://github.com/TaiBIF/camera-trap-api/wiki/identification-status)

**Comment by cjk-halodule** [comment]
@oahehc  目前 [是否需要提供 API for 樣區/子樣區名單](https://github.com/TaiBIF/camera-trap-webapp/issues/16#issuecomment-441251130) 還有需要嗎？

**Comment by trashmai** [comment]
目前切換年份呈現資料似乎有點問題，可否請 @oahehc  協助確認一下狀況？有時資料跟年份會對不起來，不知是否與送出的 request 順序與 response 回傳順序不一致導致。

**Comment by cjk-halodule** [comment]
no longer applicable.
